### ISSUE TITLE
WASM runner failing

### ISSUE THREAD

**Issue by gedw99** [devopsfaith/krakendesigner#59]
How to run this locally without docker ?

````
cd /Users/apple/workspace/go/src/github.com/devopsfaith/krakendesigner && make wasm_build
cd designer/wasm && GOOS=js GOARCH=wasm go build -o main.wasm && cd ..
cd /Users/apple/workspace/go/src/github.com/devopsfaith/krakendesigner/designer/wasm && go run main.go
main.go:13:2: build constraints exclude all Go files in /usr/local/opt/go/libexec/src/syscall/js
make: *** [go-gui-build] Error 1
````

**Comment by kpacha** [comment]
hi @gedw99 and welcome to the KrakenD community!

why are you running the `designer/wasm/main.go` file? It's the source for the WASM (available at `designer/wasm/main.wasm`) and it is already included into the designer js app

if you want to serve locally the designer, you'll need some http server. you can use npm or `goexec` in order to start a quick test server

```
$ cd ~/workspace/devops-faith/designer/designer
$ goexec 'http.ListenAndServe(":8080", http.FileServer(http.Dir(".")))'
```

cheers!
